app:
  name: ActionHub
  port: :3939
database:
  host: localhost
  port: :3306
  user: root
  password: 123456
  name: actionhub
  MaxIdleConns: 10
  MaxOpenConns: 20
redis:
  host: localhost
  port: 6379
  db: 0
  password: 